const template = {
  templateName: "PORTO",
  name: "Aaron Hanson",
  role: "FULLSTACK DEVELOPER",
  tagline: "I build scalable web apps & design systems",
  email: "aaron.hanson@example.com",
  phone: "+61 4 4254 5670",
  social: {
    github: "https://github.com/aaronhanson",
    linkedin: "https://linkedin.com/in/aaronhanson",
  },
  accentColor: "#FF3D00",
  status: "AVAILABLE FOR WORK",
  avatar: "/assets/Avatar.jpeg",
  about:
    "Fullstack developer with 5+ years of experience building production-grade web applications. I specialize in React, Node.js, and TypeScript, with a strong focus on performance optimization and clean architecture. Passionate about open-source and developer tooling.",
  resume: "",
  navLinks: [
    { id: "hero", label: "Home" },
    { id: "about", label: "About" },
    { id: "portfolio", label: "Portfolio" },
    { id: "works", label: "Works" },
    { id: "skills", label: "Skills" },
    { id: "testimonials", label: "Testimonials" },
    { id: "contact", label: "Contact" },
  ],
  skills: [
    { name: "React", icon: "SiReact" },
    { name: "Next.js", icon: "SiNextdotjs" },
    { name: "TypeScript", icon: "SiTypescript" },
    { name: "Tailwind CSS", icon: "SiTailwindcss" },
    { name: "Node.js", icon: "SiNodedotjs" },
    { name: "PostgreSQL", icon: "SiPostgresql" },
    { name: "Redis", icon: "SiRedis" },
    { name: "GraphQL", icon: "SiGraphql" },
    { name: "Docker", icon: "SiDocker" },
    { name: "Go", icon: "SiGo" },
    { name: "Linux", icon: "SiLinux" },
    { name: "Figma", icon: "SiFigma" },
  ],
  portfolio: [
    {
      id: 1,
      title: "Inventory Management System",
      category: "featured",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=INVENTORY",
      stack: ["React", "Node.js", "PostgreSQL"],
      github: "https://github.com/aaronhanson/inventory",
      demo: "",
      desc: "Built a real-time inventory tracking system reducing stock discrepancies by 40% across 3 warehouses with offline-first support.",
    },
    {
      id: 2,
      title: "Developer Docs Portal",
      category: "featured",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=DOCS",
      stack: ["Next.js", "MDX", "Tailwind"],
      github: "https://github.com/aaronhanson/docs",
      demo: "",
      desc: "Designed and built a documentation portal serving 10k+ daily developers with full-text search and versioned content.",
    },
    {
      id: 3,
      title: "Payment Gateway SDK",
      category: "featured",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=PAYMENT",
      stack: ["TypeScript", "Express", "Redis"],
      github: "https://github.com/aaronhanson/pay-sdk",
      demo: "",
      desc: "Open-source payment SDK handling $2M+ monthly transactions with 99.9% uptime and comprehensive test coverage.",
    },
    {
      id: 4,
      title: "Fitness Tracker App",
      category: "mobile",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=FITNESS",
      stack: ["React Native", "Firebase"],
      github: "https://github.com/aaronhanson/fitness",
      demo: "",
      desc: "Cross-platform fitness app with workout tracking, progress charts, and social features for 5k+ active users.",
    },
    {
      id: 5,
      title: "E-commerce Dashboard",
      category: "web",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=DASHBOARD",
      stack: ["React", "D3.js", "GraphQL"],
      github: "https://github.com/aaronhanson/dashboard",
      demo: "",
      desc: "Analytics dashboard for e-commerce merchants featuring real-time sales data, inventory alerts, and customer insights.",
    },
    {
      id: 6,
      title: "Weather API Service",
      category: "web",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=WEATHER",
      stack: ["Go", "Redis", "Docker"],
      github: "https://github.com/aaronhanson/weather",
      demo: "",
      desc: "High-performance weather aggregation API serving 1M+ daily requests with intelligent caching and rate limiting.",
    },
    {
      id: 7,
      title: "AI Chat Platform",
      category: "web",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=AI+CHAT",
      stack: ["Next.js", "Python", "WebSocket"],
      github: "https://github.com/aaronhanson/ai-chat",
      demo: "",
      desc: "Real-time AI chat platform with streaming responses, context-aware conversations, and multi-model support.",
    },
    {
      id: 8,
      title: "Habit Tracker Mobile",
      category: "mobile",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=HABITS",
      stack: ["React Native", "SQLite", "Expo"],
      github: "https://github.com/aaronhanson/habits",
      demo: "",
      desc: "Daily habit tracking app with streak counters, reminders, and visual progress charts for 10k+ users.",
    },
    {
      id: 9,
      title: "Recipe Finder App",
      category: "mobile",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=RECIPES",
      stack: ["Flutter", "Firebase", "Dart"],
      github: "https://github.com/aaronhanson/recipes",
      demo: "",
      desc: "Cross-platform recipe discovery app with ingredient-based search, meal planning, and grocery list export.",
    },
    {
      id: 10,
      title: "Brand Identity System",
      category: "design",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=BRAND",
      stack: ["Figma", "Illustrator", "Tokens"],
      github: "",
      demo: "https://dribbble.com/aaronhanson/brand",
      desc: "Complete brand identity system including logo, typography scale, color tokens, and component library for a fintech startup.",
    },
    {
      id: 11,
      title: "Dashboard UI Kit",
      category: "design",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=UI+KIT",
      stack: ["Figma", "Storybook", "CSS"],
      github: "https://github.com/aaronhanson/ui-kit",
      demo: "",
      desc: "Comprehensive UI component kit with 40+ data dashboard components, dark/light modes, and accessibility-first design.",
    },
    {
      id: 12,
      title: "Marketing Landing Pages",
      category: "design",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=LANDING",
      stack: ["Figma", "Next.js", "Tailwind"],
      github: "",
      demo: "https://aaronhanson.design/landing",
      desc: "Designed and built 8 high-conversion landing pages for SaaS products with A/B tested layouts and micro-animations.",
    },
    {
      id: 13,
      title: "Task Orchestrator",
      category: "featured",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=ORCHESTRATOR",
      stack: ["Go", "RabbitMQ", "Docker"],
      github: "https://github.com/aaronhanson/orchestrator",
      demo: "",
      desc: "Distributed task orchestrator managing 10k+ concurrent workflows with priority queuing, retries, and real-time monitoring.",
    },
    {
      id: 14,
      title: "Monitoring Stack",
      category: "featured",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=MONITORING",
      stack: ["React", "Grafana", "Prometheus"],
      github: "https://github.com/aaronhanson/monitoring",
      demo: "",
      desc: "Full observability platform with custom dashboards, alerting rules, and anomaly detection serving 50+ microservices.",
    },
    {
      id: 15,
      title: "API Gateway",
      category: "featured",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=API+GATEWAY",
      stack: ["Node.js", "Redis", "Kong"],
      github: "https://github.com/aaronhanson/gateway",
      demo: "",
      desc: "High-throughput API gateway handling 100k+ RPM with rate limiting, auth, caching, and granular usage analytics.",
    },
    {
      id: 16,
      title: "CMS Platform",
      category: "web",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=CMS",
      stack: ["Next.js", "PostgreSQL", "TipTap"],
      github: "https://github.com/aaronhanson/cms",
      demo: "",
      desc: "Headless CMS with block-based editor, media library, role-based access, and webhook integrations for enterprise teams.",
    },
    {
      id: 17,
      title: "Video Platform",
      category: "web",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=VIDEO",
      stack: ["React", "FFmpeg", "WebSocket"],
      github: "https://github.com/aaronhanson/video",
      demo: "",
      desc: "Video processing platform supporting transcoding, adaptive bitrate streaming, and real-time captions for 10k+ daily uploads.",
    },
    {
      id: 18,
      title: "Form Builder",
      category: "web",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=FORM+BUILDER",
      stack: ["React", "Node.js", "MongoDB"],
      github: "https://github.com/aaronhanson/forms",
      demo: "",
      desc: "Drag-and-drop form builder with conditional logic, file uploads, email notifications, and submission analytics dashboard.",
    },
    {
      id: 19,
      title: "Budget Tracker",
      category: "mobile",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=BUDGET",
      stack: ["React Native", "SQLite", "Chart.js"],
      github: "https://github.com/aaronhanson/budget",
      demo: "",
      desc: "Personal finance app with expense categorization, budget limits, recurring transaction tracking, and monthly spending insights.",
    },
    {
      id: 20,
      title: "Language Learn",
      category: "mobile",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=LANGUAGE",
      stack: ["Flutter", "Firebase", "Gemini"],
      github: "https://github.com/aaronhanson/lingo",
      demo: "",
      desc: "Language learning app with AI-powered conversations, spaced repetition flashcards, pronunciation scoring, and progress tracking.",
    },
    {
      id: 21,
      title: "Meditation App",
      category: "mobile",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=MEDITATION",
      stack: ["React Native", "Expo", "Firebase"],
      github: "https://github.com/aaronhanson/mindful",
      demo: "",
      desc: "Guided meditation app with ambient soundscapes, session timers, streak tracking, and personalized mindfulness recommendations.",
    },
    {
      id: 22,
      title: "Icon Library",
      category: "design",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=ICONS",
      stack: ["Figma", "SVG", "React"],
      github: "https://github.com/aaronhanson/icons",
      demo: "https://aaronhanson.design/icons",
      desc: "Custom icon library with 200+ consistent SVG icons, React component export, and Figma plugin for seamless design handoff.",
    },
    {
      id: 23,
      title: "Wireframe Kit",
      category: "design",
      img: "https://placehold.co/600x400/FF3D00/FFFFFF?text=WIREFRAME",
      stack: ["Figma", "Auto Layout", "Variables"],
      github: "",
      demo: "https://aaronhanson.design/wireframes",
      desc: "Comprehensive wireframe kit with 60+ pre-built screens, responsive auto-layout components, and interactive prototype templates.",
    },
    {
      id: 24,
      title: "Motion System",
      category: "design",
      img: "https://placehold.co/600x400/1A1A1A/FFFFFF?text=MOTION",
      stack: ["Figma", "Lottie", "GSAP"],
      github: "https://github.com/aaronhanson/motion",
      demo: "https://aaronhanson.design/motion",
      desc: "Design system motion library with micro-interactions, page transitions, loading states, and Lottie animation export pipeline.",
    },
  ],
  categories: [
    { id: "featured", title: "Featured" },
    { id: "web", title: "Web App" },
    { id: "mobile", title: "Mobile App" },
    { id: "design", title: "Design" },
  ],
  works: [
    {
      id: "1",
      year: "2024",
      title: "TechCorp Studio",
      role: "Senior Fullstack Developer",
      desc: "Led a team of 5 engineers rebuilding the core platform from monolith to microservices, reducing deployment time by 70%.",
    },
    {
      id: "2",
      year: "2023",
      title: "DataFlow Inc.",
      role: "Fullstack Developer",
      desc: "Developed real-time data pipeline processing 50k events/sec using Node.js and Kafka, serving enterprise clients.",
    },
    {
      id: "3",
      year: "2022",
      title: "WebForge Agency",
      role: "Frontend Developer",
      desc: "Built 15+ client-facing web applications using React and Next.js, delivering projects on time and under budget.",
    },
    {
      id: "4",
      year: "2021",
      title: "Startup Labs",
      role: "Junior Developer",
      desc: "Contributed to early-stage SaaS product from concept to launch, handling full-stack features and CI/CD setup.",
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Sarah Chen",
      title: "CTO, TechCorp Studio",
      img: "https://randomuser.me/api/portraits/women/44.jpg",
      desc: "Aaron delivered our platform rewrite ahead of schedule. His architectural decisions saved us months of technical debt. Highly recommend.",
      featured: false,
    },
    {
      id: 2,
      name: "Marcus Webb",
      title: "CEO, DataFlow Inc.",
      img: "https://randomuser.me/api/portraits/men/32.jpg",
      desc: "One of the best engineers I've worked with. Aaron's ability to bridge frontend and backend seamlessly made him invaluable to our team.",
      featured: true,
    },
    {
      id: 3,
      name: "Emily Torres",
      title: "Product Lead, WebForge",
      img: "https://randomuser.me/api/portraits/women/68.jpg",
      desc: "Aaron consistently delivered high-quality work under tight deadlines. Clients always praised his attention to detail and communication.",
      featured: false,
    },
    {
      id: 4,
      name: "David Park",
      title: "Lead Engineer, Startup Labs",
      img: "https://randomuser.me/api/portraits/men/75.jpg",
      desc: "Aaron's mentorship elevated our entire engineering team. He established code review practices and testing standards we still use today.",
      featured: false,
    },
    {
      id: 5,
      name: "Jessica Kim",
      title: "Design Director, Pixel & Co.",
      img: "https://randomuser.me/api/portraits/women/90.jpg",
      desc: "Collaborating with Aaron on design-to-code handoff was seamless. His understanding of design systems and component architecture is outstanding.",
      featured: true,
    },
    {
      id: 6,
      name: "Ryan O'Brien",
      title: "Founder, DevForge",
      img: "https://randomuser.me/api/portraits/men/91.jpg",
      desc: "Aaron built our entire MVP in 8 weeks. The codebase was so clean we never needed a rewrite. Rare to find that level of quality in a founder.",
      featured: false,
    },
  ],
};

export default template;
