const template = {
  templateName: "PORTO",
  name: "Your Name",
  role: "YOUR_ROLE",
  tagline: "Your tagline here",
  email: "hello@example.com",
  phone: "+00 000 000 000",
  social: {
    github: "https://github.com/",
    linkedin: "https://linkedin.com/in/",
  },
  accentColor: "#FF3D00",
  status: "AVAILABLE FOR WORK",
  navLinks: [
    { id: "hero", label: "Home" },
    { id: "portfolio", label: "Portfolio" },
    { id: "works", label: "Works" },
    { id: "skills", label: "Skills" },
    { id: "testimonials", label: "Testimonials" },
    { id: "contact", label: "Contact" },
  ],
  skills: [
    { name: "Skill 1", level: 90 },
    { name: "Skill 2", level: 80 },
    { name: "Skill 3", level: 75 },
    { name: "Skill 4", level: 70 },
    { name: "Skill 5", level: 85 },
    { name: "Skill 6", level: 65 },
  ],
  portfolio: [
    { id: 1, title: "Project Alpha", category: "featured", img: "" },
    { id: 2, title: "Project Beta", category: "featured", img: "" },
    { id: 3, title: "Project Gamma", category: "featured", img: "" },
    { id: 4, title: "Project Delta", category: "mobile", img: "" },
    { id: 5, title: "Project Epsilon", category: "web", img: "" },
    { id: 6, title: "Project Zeta", category: "mobile", img: "" },
  ],
  categories: [
    { id: "featured", title: "Featured" },
    { id: "web", title: "Web App" },
    { id: "mobile", title: "Mobile App" },
    { id: "design", title: "Design" },
  ],
  works: [
    {
      id: "1",
      year: "2024",
      title: "Company Alpha",
      role: "Senior Developer",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    },
    {
      id: "2",
      year: "2023",
      title: "Company Beta",
      role: "Fullstack Developer",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    },
    {
      id: "3",
      year: "2022",
      title: "Company Gamma",
      role: "Frontend Developer",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    },
  ],
  testimonials: [
    {
      id: 1,
      name: "Client One",
      title: "CEO, Company A",
      img: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      featured: false,
    },
    {
      id: 2,
      name: "Client Two",
      title: "CTO, Company B",
      img: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      featured: true,
    },
    {
      id: 3,
      name: "Client Three",
      title: "Founder, Company C",
      img: "",
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      featured: false,
    },
  ],
};

export default template;
